command: ['streamlit', 'run', 'app.py', '--server.port', '8000', '--server.address', '0.0.0.0']
env:
  - name: PGHOST
    value: "ep-hidden-mouse-d1gj4kga.database.us-west-2.cloud.databricks.com"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGUSER
    value: "56dfcd38-371a-40af-b14d-32f7eb8b3b2f"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: ENDPOINT_NAME
    value: "projects/lakebaseankur/branches/production/endpoints/primary"
